# Site settings
title:       die the death
email:       divided.joy@gmail.com
author:      Una Owen
description: "the weight of a sin depends on the person measuring it"
baseurl:     ""
url:         "http://dividead.github.io/"

# Google analytics
google_analytics: UA-55289510-2

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: dividead
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
